### ISSUE TITLE
Consider removing auto-flex for items

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-ordered-layout#19]
Is `flex: 1 1 auto;` for the slotted items really beneficial?

https://github.com/vaadin/vaadin-ordered-layout/blob/master/vaadin-vertical-layout.html#L39
https://github.com/vaadin/vaadin-ordered-layout/blob/master/vaadin-horizontal-layout.html#L38

IMO it makes it more difficult for a developer to let one single item flex in the layout (i.e. take all unused space).

**Comment by heruan** [comment]
Personally I find it useful in the horizontal layout, since it's what I'd expect i.e. fit the parent width by default (in my current tests it helps avoiding many `width: 100%` or `flex-grow: 1`).

In vertical layout though, I'm always overriding it with `flex-grow: 0` since in most cases I don't want the contents to fit vertically (nested layouts maybe, but not concrete elements).

**Comment by jouni** [comment]
> Personally I find it useful in the horizontal layout, since it's what I'd expect i.e. fit the parent width by default (in my current tests it helps avoiding many width: 100% or flex-grow: 1).

If you only want one of the items to grow, how would you do that? I think it’s unreasonable to have to do the opposite, set `flex-grow: 0;` on all other items. 

I think we need convenience attributes or something for this so that you can easily set all items to flex/expand/grow, or just a single item, and the defaults would be that no items flex/expand/grow.

**Comment by YuriyVaadin** [comment]
> If you only want one of the items to grow, how would you do that? I think it’s unreasonable to have to do the opposite, set flex-grow: 0; on all other items.

The problem is that the other way around you will need to specify `flex-grow` to make only one item to grow.

> Personally I find it useful in the horizontal layout, since it's what I'd expect i.e. fit the parent width by default

As this functionality is expected to be in horizontal layout it should be implemented the same way in vertical layout. 

For users it is much more difficult to come up with an idea how to make items grow to the full width/height. The only proper way to do that is to use `flex` as setting the `height` and `width` to `100%` will lead to the problems with exact values of those properties (i.e when height/width is specified on host). That will cause problems with defining gaps between items as there will be extra space left.

On other hand for making items not to grow we can use **two** proper ways:
1. To add extra DOM element (div) to wrap internal elements. Kind of `Common Usage` examples

![screen shot 2017-12-07 at 11 23 32](https://user-images.githubusercontent.com/29372419/33707739-2333e6d0-db41-11e7-840d-bab2969e0d84.png)

1. Using the same way with specifying `flex` on items. What can be added to `Advanced Usage`.

![screen shot 2017-12-07 at 11 31 15](https://user-images.githubusercontent.com/29372419/33708105-3097926c-db42-11e7-8af8-afc318d4a0fd.png)

All of those examples will be documented as well.

**Comment by jouni** [comment]
I still say it’s backwards to have items flex by default. This was also the sentiment I got from our UX team designers.

**Comment by jouni** [comment]
I have a prototype ready for sharing in the `default-behavior` branch, with an added test case in `test/use-cases.html` (some made up examples that somewhat represent some common use cases).
