### ISSUE TITLE
Decide and (or not to) implement child stretching change

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-ordered-layout#24]

**Comment by jouni** [comment]
To be clear, this issue is about changing from the current default `align-items: stretch;` to `align-items: flex-start;`. Correct me if I’m wrong.

I’m still in favor of this change, it seems like the more expected results for this type of layout, even though it will be different from a standard flex container.

**Comment by web-padawan** [comment]
Discussed this in person today and confirmed the intent to us `flex-start`. Working on this as well as #19 now
