### ISSUE TITLE
HorizontalLayout and FlexComponent.JustifyContentMode.BETWEEN yields unexpected results

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-ordered-layout#49]
@mvysny commented on [Fri Apr 20 2018](https://github.com/vaadin/vaadin-ordered-layout-flow/issues/54)

My use case is to have two child `h3` and `h4` in a `HorizontalLayout`, showing a "Welcome" text justified to the left, "App Name" justified to the right. In hopes to achieve that, I have set h3 and h4 to wrap its contents and set the parent `HorizontalLayout` to "Between", hoping for the `HorizontalLayout` to add space between those two items, pushing them apart.

However, there is a third item: an invisible `::before` which is also considered by the flex layout engine, and hence the flex layout engine distributes space between the `::before` and `h3`.

Please see the screenshot attached. Could it be possible to remove the `::before` from `HorizontalLayout`?

![screenshot from 2018-04-20 18-33-38](https://user-images.githubusercontent.com/254091/39060583-70e00272-44ca-11e8-9715-54b1bc6331a6.png)

**Comment by web-padawan** [comment]
This pseudo element is intended to make [spacing](https://github.com/vaadin/vaadin-ordered-layout/blob/master/theme/lumo/vaadin-horizontal-layout.html#L32) theme variation (and all of its options, like `spacing-xs` etc) work as expected. To my understanding, when using one of these, user is unlikely to be expected manage the `justify-content` himself.

Consider using the `spacing` theme only when you need equal gaps between the items, or otherwise (like in this case) just remove it and then align items as necessary.

We might need to document this better.

**Comment by mvysny** [comment]
Thank you, disabling spacing indeed helped.
